//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.01.06 at 04:00:07 PM WEST 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://bankati.com/cmi/payment", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.bankati.cmi.payment;
