spring:
  application:
    name: Cmi-ms
    admin:
      enabled: false
  jmx:
    unique-names: true
  datasource:
    url: jdbc:postgresql://localhost:5432/bankati2
    driver-class-name: org.postgresql.Driver
    username: root
    password: root
  jpa:
    database-platform: ${SPRING_JPA_DATABASE_PLATFORM:org.hibernate.dialect.PostgreSQLDialect}
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
eureka:
  client:
    region: default
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://localhost:8081/eureka/
server:
  port: 9093