spring:
  application:
    name: cmi-ms
    admin:
      enabled: false
  jmx:
    unique-names: true
  datasource:
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.postgresql.Driver}
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://pg-ai-credit-scoring-project-project22-2002.k.aivencloud.com:28624/defaultdb?user=avnadmin&password=AVNS_iGYa-583_6rRE3zWRfe}
    username: ${SPRING_DATASOURCE_USERNAME:avnadmin}
    password: ${SPRING_DATASOURCE_PASSWORD:AVNS_iGYa-583_6rRE3zWRfe}
  jpa:
    database-platform: ${SPRING_JPA_DATABASE_PLATFORM:org.hibernate.dialect.PostgreSQLDialect}
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
eureka:
  client:
    region: default
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://localhost:8081/eureka/
server:
  port: 9093