//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.01.08 at 04:57:27 PM WEST 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://bankati.com/cmi/transaction", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.bankati.cmi.transaction;
